[package]
name = "helion"
version = "0.2.0"
authors = ["bryal <96.bryal@gmail.com>"]

[dependencies]
rustc-serialize = "*"
dxgcap = "*"
clock_ticks = "*"

[dependencies.se_rs_ial]
git = "https://github.com/bryal/se-rs-ial"
